const fs = require('fs');
const path = require('path');

const RECIPES_PATH = path.join(__dirname, '../data/recipes.json');

// Batch 2: 20 More Authentic Filipino Recipes
const newRecipes = [
  {
    id: 'kare-kare-seafood',
    slug: 'seafood-kare-kare',
    title: 'Seafood Kare-Kare',
    summary:
      'A lighter version of the classic peanut stew featuring shrimp, squid, and mussels.',
    description:
      'For those who love the rich peanut sauce of Kare-Kare but prefer seafood over oxtail. This version features fresh shrimp, squid rings, and mussels simmered in a thick, golden peanut sauce with vegetables.',
    heroImage: '/images/recipes/seafood-kare-kare.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 5,
    prepTime: '20 mins',
    cookTime: '30 mins',
    totalTime: '50 mins',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviews: 65,
    dietaryTags: ['pescetarian', 'contains-peanut'],
    matchIngredients: [
      'shrimp',
      'squid',
      'mussels',
      'peanut-butter',
      'annatto',
      'string-beans',
      'eggplant',
      'pechay',
    ],
    ingredients: [
      { name: 'Shrimp, large', amount: '300g' },
      { name: 'Squid, sliced into rings', amount: '300g' },
      { name: 'Mussels (Tahong), cleaned', amount: '500g' },
      { name: 'Peanut butter', amount: '3/4 cup' },
      { name: 'Annatto water', amount: '1/2 cup' },
      { name: 'String beans (sitaw)', amount: '1 bundle' },
      { name: 'Eggplant, sliced', amount: '2 pcs' },
      { name: 'Pechay (Bok Choy)', amount: '2 bundles' },
      { name: 'Garlic & Onion', amount: 'minced' },
      { name: 'Fish stock', amount: '3 cups' },
      { name: 'Cornstarch (slurry)', amount: '2 tbsp' },
    ],
    steps: [
      'Blanch the vegetables separately and set aside.',
      'Sauté garlic and onion. Add peanut butter and fish stock. Mix well.',
      'Add annatto water for color. Bring to a simmer.',
      'Thicken with cornstarch slurry if needed.',
      'Add the seafood (shrimp, squid, mussels). Cook for 3-5 minutes until done. Do not overcook.',
      'Add the blanched vegetables.',
      'Serve hot with bagoong (shrimp paste) on the side.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/seafood-kare-kare',
    nutrition: { calories: 380, protein: 35, carbs: 15, fat: 22, fiber: 4, sodium: 650 },
  },
  {
    id: 'chicken-inasal',
    slug: 'chicken-inasal-bacolod',
    title: 'Chicken Inasal (Bacolod Style)',
    summary: 'Grilled chicken marinated in lemongrass, calamansi, and annatto oil.',
    description:
      'The pride of Bacolod. Chicken pieces are marinated in a unique blend of vinegar, calamansi, lemongrass, and ginger, then grilled over charcoal while being basted with annatto oil (chicken oil).',
    heroImage: '/images/recipes/chicken-inasal.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '30 mins',
    cookTime: '25 mins',
    totalTime: '55 mins',
    difficulty: 'Intermediate',
    rating: 4.9,
    reviews: 150,
    dietaryTags: ['high-protein', 'gluten-free'],
    matchIngredients: [
      'chicken-thigh',
      'lemongrass',
      'calamansi',
      'ginger',
      'garlic',
      'vinegar',
      'annatto',
    ],
    ingredients: [
      { name: 'Chicken leg quarters', amount: '4 pcs' },
      { name: 'Lemongrass (tanglad), chopped', amount: '2 stalks' },
      { name: 'Calamansi juice', amount: '1/4 cup' },
      { name: 'Vinegar', amount: '1/4 cup' },
      { name: 'Ginger, minced', amount: '1 thumb-sized' },
      { name: 'Garlic, minced', amount: '1 head' },
      { name: 'Brown sugar', amount: '2 tbsp' },
      { name: 'Annatto oil (for basting)', amount: '1/2 cup' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    steps: [
      'Combine lemongrass, calamansi, vinegar, ginger, garlic, sugar, salt, and pepper in a bowl.',
      'Marinate chicken for at least 3 hours or overnight.',
      'Prepare charcoal grill.',
      'Grill chicken over medium heat, turning occasionally.',
      'Bast generously with annatto oil/chicken oil while grilling.',
      'Cook until internal temperature reaches 165°F (74°C).',
      'Serve with garlic rice and spiced vinegar.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/chicken-inasal',
    nutrition: { calories: 450, protein: 40, carbs: 8, fat: 28, fiber: 1, sodium: 780 },
  },
  {
    id: 'la paz-batchoy',
    slug: 'la-paz-batchoy-authentic',
    title: 'La Paz Batchoy',
    summary:
      "Iloilo's famous noodle soup with pork offal, crushed chicharon, and raw egg.",
    description:
      'A rich noodle soup originating from La Paz, Iloilo. It features miki noodles in a flavorful broth made from pork and beef bones, topped with pork liver, intestines, crushed chicharon, and a raw egg cracked on top.',
    heroImage: '/images/recipes/batchoy.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '30 mins',
    cookTime: '3 hrs',
    totalTime: '3 hrs 30 mins',
    difficulty: 'Advanced',
    rating: 4.8,
    reviews: 92,
    dietaryTags: [],
    matchIngredients: [
      'pork-belly',
      'egg',
      'garlic',
      'onion',
      'scallions',
      'shrimp-paste',
    ],
    ingredients: [
      { name: 'Miki noodles (fresh egg noodles)', amount: '500g' },
      { name: 'Pork bones & Beef bones', amount: '1 kg' },
      { name: 'Pork belly, boiled and sliced', amount: '200g' },
      { name: 'Pork liver, sliced', amount: '150g' },
      { name: 'Shrimp paste (bagoong)', amount: '1 tbsp' },
      { name: 'Chicharon, crushed', amount: '1 cup' },
      { name: 'Garlic, fried', amount: '1/2 cup' },
      { name: 'Spring onions', amount: '1/4 cup' },
      { name: 'Raw eggs', amount: '4 pcs' },
      { name: 'Sugar', amount: '1 tsp' },
    ],
    steps: [
      'Boil bones with onions and salt for 3 hours to make a rich stock. Strain.',
      'Add shrimp paste and sugar to the broth. Keep boiling hot.',
      'Blanch noodles and place in bowls.',
      'Top with sliced pork belly, liver, and intestines (if using).',
      'Pour boiling broth over the noodles.',
      'Crack a raw egg on top.',
      'Garnish generously with crushed chicharon, fried garlic, and spring onions.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/la-paz-batchoy',
    nutrition: { calories: 520, protein: 35, carbs: 45, fat: 22, fiber: 2, sodium: 1100 },
  },
  {
    id: 'pinapaitan',
    slug: 'pinapaitan-bitter-stew',
    title: 'Pinapaitan (Papaitan)',
    summary: 'A bitter goat or beef stew flavored with bile and tamarind.',
    description:
      'An Ilocano delicacy known for its distinct bitter flavor from bile (papait). Made with goat or beef innards (tripe, liver, heart) and flavored with ginger, garlic, onion, and tamarind or calamansi.',
    heroImage: '/images/recipes/pinapaitan.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '30 mins',
    cookTime: '2 hrs',
    totalTime: '2 hrs 30 mins',
    difficulty: 'Advanced',
    rating: 4.5,
    reviews: 40,
    dietaryTags: ['high-protein'],
    matchIngredients: ['beef-shank', 'ginger', 'onion', 'garlic', 'chili', 'calamansi'],
    ingredients: [
      { name: 'Beef or Goat innards (tripe, liver, heart)', amount: '1 kg' },
      { name: 'Beef bile (papait)', amount: '1/4 cup' },
      { name: 'Ginger, sliced', amount: '2 thumb-sized' },
      { name: 'Onion, chopped', amount: '1 large' },
      { name: 'Garlic, minced', amount: '1 head' },
      { name: 'Calamansi juice', amount: '1/4 cup' },
      { name: 'Green chilies (siling haba)', amount: '4 pcs' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    steps: [
      'Clean innards thoroughly. Boil with ginger until tender. Slice into small pieces.',
      'Sauté garlic, onion, and ginger.',
      'Add the sliced innards and cook until browned.',
      'Pour in broth (from boiling) or water. Simmer.',
      'Add bile gradually until desired bitterness is reached.',
      'Add calamansi juice and green chilies.',
      'Simmer for another 15 minutes. Serve hot.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/pinapaitan',
    nutrition: { calories: 320, protein: 45, carbs: 4, fat: 14, fiber: 1, sodium: 600 },
  },
  {
    id: 'lechon-paksiw',
    slug: 'lechon-paksiw-stew',
    title: 'Lechon Paksiw',
    summary: 'Leftover lechon stewed in a sweet and tangy liver sauce.',
    description:
      'The best way to repurpose leftover Lechon or Lechon Kawali. The meat is simmered in a sauce made of vinegar, sugar, and lechon sauce (liver sauce), creating a sweet, tangy, and savory stew.',
    heroImage: '/images/recipes/lechon-paksiw.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '10 mins',
    cookTime: '40 mins',
    totalTime: '50 mins',
    difficulty: 'Easy',
    rating: 4.8,
    reviews: 85,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'pork-belly',
      'lechon-sauce',
      'vinegar',
      'sugar',
      'garlic',
      'onion',
      'bay-leaves',
    ],
    ingredients: [
      { name: 'Leftover Lechon or Roast Pork', amount: '1 kg' },
      { name: 'Lechon sauce (Mang Tomas)', amount: '1 bottle (330g)' },
      { name: 'Vinegar', amount: '1/2 cup' },
      { name: 'Sugar', amount: '1/2 cup' },
      { name: 'Garlic, minced', amount: '1 head' },
      { name: 'Onion, chopped', amount: '1 medium' },
      { name: 'Bay leaves', amount: '3 pcs' },
      { name: 'Peppercorns', amount: '1 tsp' },
      { name: 'Water', amount: '1 cup' },
    ],
    steps: [
      'In a pot, combine leftover lechon, garlic, onion, bay leaves, peppercorns, vinegar, sugar, and water.',
      'Bring to a boil without stirring.',
      'Pour in the lechon sauce.',
      'Simmer on low heat for 30-40 minutes until meat is very tender and sauce thickens.',
      'Adjust sweetness or sourness to taste.',
      'Serve with rice.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/lechon-paksiw',
    nutrition: { calories: 480, protein: 35, carbs: 25, fat: 28, fiber: 1, sodium: 850 },
  },
  {
    id: 'adobong-kangkong',
    slug: 'adobong-kangkong-water-spinach',
    title: 'Adobong Kangkong',
    summary: 'Water spinach sautéed in soy sauce, vinegar, and lots of garlic.',
    description:
      'A simple, healthy, and affordable vegetable dish. Kangkong (water spinach) leaves and stalks are cooked adobo-style with soy sauce, vinegar, garlic, and sometimes topped with crispy pork bits.',
    heroImage: '/images/recipes/adobong-kangkong.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 3,
    prepTime: '10 mins',
    cookTime: '10 mins',
    totalTime: '20 mins',
    difficulty: 'Easy',
    rating: 4.6,
    reviews: 60,
    dietaryTags: ['vegetarian', 'vegan-optional'],
    matchIngredients: ['kangkong', 'garlic', 'onion', 'soy-sauce', 'vinegar', 'pepper'],
    ingredients: [
      { name: 'Kangkong (Water Spinach), cleaned', amount: '2 bundles' },
      { name: 'Garlic, minced', amount: '5 cloves' },
      { name: 'Onion, chopped', amount: '1 small' },
      { name: 'Soy sauce', amount: '3 tbsp' },
      { name: 'Vinegar', amount: '2 tbsp' },
      { name: 'Black pepper', amount: '1/2 tsp' },
      { name: 'Oil', amount: '1 tbsp' },
      { name: 'Toasted garlic (topping)', amount: '1 tbsp' },
    ],
    steps: [
      'Separate kangkong leaves from stalks.',
      'Sauté garlic and onion in oil until fragrant.',
      'Add the kangkong stalks first (they take longer to cook). Stir fry for 1 minute.',
      'Add soy sauce and vinegar. Do not stir for a minute.',
      'Add the leaves and pepper. Cover and let steam for 1 minute.',
      'Toss everything together until leaves are wilted but still bright green.',
      'Top with toasted garlic and serve.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/adobong-kangkong',
    nutrition: { calories: 80, protein: 4, carbs: 10, fat: 4, fiber: 3, sodium: 450 },
  },
  {
    id: 'picadillo',
    slug: 'picadillo-giniling',
    title: 'Picadillo (Giniling na Baka)',
    summary: 'Ground beef stew with potatoes, carrots, raisins, and bell peppers.',
    description:
      'A versatile ground beef dish (giniling) cooked in tomato sauce with diced potatoes, carrots, and bell peppers. Often includes raisins for a touch of sweetness. Great with rice or as a filling for bread.',
    heroImage: '/images/recipes/picadillo.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '15 mins',
    cookTime: '25 mins',
    totalTime: '40 mins',
    difficulty: 'Easy',
    rating: 4.7,
    reviews: 75,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'ground-beef',
      'potato',
      'carrot',
      'bell-pepper',
      'raisins',
      'tomato',
      'garlic',
      'onion',
    ],
    ingredients: [
      { name: 'Ground beef', amount: '500g' },
      { name: 'Potatoes, diced', amount: '1 cup' },
      { name: 'Carrots, diced', amount: '1 cup' },
      { name: 'Red bell pepper, diced', amount: '1 pc' },
      { name: 'Raisins', amount: '1/4 cup' },
      { name: 'Tomato sauce', amount: '1 cup' },
      { name: 'Garlic & Onion', amount: 'minced' },
      { name: 'Soy sauce', amount: '1 tbsp' },
      { name: 'Water', amount: '1/2 cup' },
    ],
    steps: [
      'Sauté garlic and onion.',
      'Add ground beef and cook until brown.',
      'Add soy sauce and tomato sauce. Simmer for 5 minutes.',
      'Add water, potatoes, and carrots. Cover and cook until veggies are tender.',
      'Add bell peppers and raisins. Simmer for another 3 minutes.',
      'Season with salt and pepper.',
      'Serve with rice or bread.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/picadillo',
    nutrition: { calories: 350, protein: 25, carbs: 22, fat: 18, fiber: 4, sodium: 620 },
  },
  {
    id: 'maja-blanca',
    slug: 'maja-blanca-coconut-pudding',
    title: 'Maja Blanca',
    summary: 'Creamy coconut pudding with corn kernels, topped with cheese or latik.',
    description:
      "A popular Filipino dessert often served at fiestas. It's a smooth, creamy coconut pudding thickened with cornstarch, mixed with sweet corn kernels, and topped with cheese or toasted coconut curds.",
    heroImage: '/images/recipes/maja-blanca.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 8,
    prepTime: '10 mins',
    cookTime: '20 mins',
    totalTime: '30 mins',
    difficulty: 'Easy',
    rating: 4.8,
    reviews: 88,
    dietaryTags: ['vegetarian', 'gluten-free', 'sweet'],
    matchIngredients: ['coconut-milk', 'corn', 'cornstarch', 'sugar', 'milk', 'cheese'],
    ingredients: [
      { name: 'Coconut milk', amount: '4 cups' },
      { name: 'Cornstarch', amount: '3/4 cup' },
      { name: 'Sugar', amount: '3/4 cup' },
      { name: 'Sweet corn kernels (canned)', amount: '1 cup' },
      { name: 'Condensed milk', amount: '1/2 cup' },
      { name: 'Fresh milk', amount: '1/2 cup' },
      { name: 'Cheese, grated (topping)', amount: '1/2 cup' },
    ],
    steps: [
      'In a pot, mix coconut milk, sugar, condensed milk, and sweet corn. Bring to a gentle boil.',
      'Dissolve cornstarch in fresh milk.',
      'Lower heat and slowly pour the cornstarch mixture into the pot while stirring constantly.',
      'Cook until the mixture thickens to a pudding consistency.',
      'Pour into a tray or mold. Smooth the top.',
      'Sprinkle grated cheese on top.',
      'Let cool and set in the refrigerator before slicing.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/maja-blanca',
    nutrition: { calories: 320, protein: 4, carbs: 45, fat: 15, fiber: 1, sodium: 120 },
  },
  {
    id: 'chicken-macaroni-salad',
    slug: 'chicken-macaroni-salad-filipino',
    title: 'Filipino Chicken Macaroni Salad',
    summary: 'Sweet and savory pasta salad with chicken, pineapple, raisins, and cheese.',
    description:
      'A staple at Filipino parties and Christmas dinners. Elbow macaroni is tossed in a sweetened mayonnaise dressing with shredded chicken, pineapple tidbits, carrots, raisins, and cheese cubes.',
    heroImage: '/images/recipes/macaroni-salad.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 8,
    prepTime: '20 mins',
    cookTime: '15 mins',
    totalTime: '35 mins',
    difficulty: 'Easy',
    rating: 4.7,
    reviews: 65,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'chicken-breast',
      'carrot',
      'raisins',
      'cheese',
      'onion',
      'mayonnaise',
    ],
    ingredients: [
      { name: 'Elbow macaroni', amount: '400g' },
      { name: 'Chicken breast, boiled and shredded', amount: '2 cups' },
      { name: 'Mayonnaise', amount: '2 cups' },
      { name: 'Pineapple tidbits, drained', amount: '1 cup' },
      { name: 'Carrots, minced', amount: '1/2 cup' },
      { name: 'Raisins', amount: '1/2 cup' },
      { name: 'Cheese, cubed', amount: '1/2 cup' },
      { name: 'Onion, minced', amount: '1 small' },
      { name: 'Condensed milk', amount: '1/4 cup' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    steps: [
      'Cook macaroni according to package instructions. Drain and let cool.',
      'In a large bowl, combine mayonnaise and condensed milk.',
      'Add chicken, pineapple, carrots, raisins, cheese, and onion.',
      'Fold in the macaroni until well coated.',
      'Season with salt and pepper.',
      'Refrigerate for at least 1 hour before serving.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/chicken-macaroni-salad',
    nutrition: { calories: 420, protein: 15, carbs: 45, fat: 22, fiber: 2, sodium: 450 },
  },
  {
    id: 'beef-mechado',
    slug: 'beef-mechado-tomato-stew',
    title: 'Beef Mechado',
    summary: 'Tangy beef stew with potatoes and carrots in a rich tomato sauce.',
    description:
      'Similar to Kaldereta and Afritada but distinct for its use of soy sauce and citrus (calamansi or lemon) in the tomato sauce, giving it a deeper, tangier flavor profile. Often made with larded beef.',
    heroImage: '/images/recipes/beef-mechado.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 5,
    prepTime: '20 mins',
    cookTime: '1 hr 30 mins',
    totalTime: '1 hr 50 mins',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 55,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'beef-brisket',
      'potato',
      'carrot',
      'bell-pepper',
      'tomato',
      'soy-sauce',
      'calamansi',
    ],
    ingredients: [
      { name: 'Beef chunks (chuck or brisket)', amount: '1 kg' },
      { name: 'Potatoes, quartered', amount: '2 medium' },
      { name: 'Carrots, sliced', amount: '2 medium' },
      { name: 'Tomato sauce', amount: '1 cup' },
      { name: 'Soy sauce', amount: '1/4 cup' },
      { name: 'Calamansi juice', amount: '3 tbsp' },
      { name: 'Bell pepper, sliced', amount: '1 pc' },
      { name: 'Garlic & Onion', amount: 'minced' },
      { name: 'Bay leaves', amount: '2 pcs' },
      { name: 'Water', amount: '2 cups' },
    ],
    steps: [
      'Marinate beef in soy sauce and calamansi for 30 minutes.',
      'Sear beef in a pot until browned. Set aside.',
      'Sauté garlic and onion. Return beef to pot.',
      'Add tomato sauce and water. Bring to a boil.',
      'Simmer for 1-1.5 hours until beef is tender.',
      'Add potatoes and carrots. Cook until tender.',
      'Add bell peppers and simmer for 2 minutes.',
      'Serve hot.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/beef-mechado',
    nutrition: { calories: 450, protein: 35, carbs: 22, fat: 24, fiber: 4, sodium: 850 },
  },
  {
    id: 'ginataang-tilapia',
    slug: 'ginataang-tilapia-coconut',
    title: 'Ginataang Tilapia',
    summary: 'Fried tilapia stewed in rich coconut milk with pechay.',
    description:
      'A creamy and savory fish dish. Tilapia is fried first to keep its shape, then simmered in coconut milk flavored with ginger, garlic, and onions, with leafy greens like pechay or spinach added at the end.',
    heroImage: '/images/recipes/ginataang-tilapia.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '15 mins',
    cookTime: '25 mins',
    totalTime: '40 mins',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviews: 48,
    dietaryTags: ['pescetarian'],
    matchIngredients: [
      'tilapia',
      'coconut-milk',
      'pechay',
      'ginger',
      'garlic',
      'onion',
      'chili',
    ],
    ingredients: [
      { name: 'Tilapia, cleaned', amount: '2 large' },
      { name: 'Coconut milk', amount: '2 cups' },
      { name: 'Pechay or Spinach', amount: '1 bundle' },
      { name: 'Ginger, sliced', amount: '1 thumb-sized' },
      { name: 'Garlic & Onion', amount: 'minced' },
      { name: 'Green chili', amount: '2 pcs' },
      { name: 'Salt and pepper', amount: 'to taste' },
      { name: 'Oil', amount: 'for frying' },
    ],
    steps: [
      'Season tilapia with salt. Fry until golden brown. Set aside.',
      'In a pan, sauté garlic, onion, and ginger.',
      'Pour in coconut milk and bring to a simmer.',
      'Add the fried tilapia and green chilies.',
      'Simmer for 5-10 minutes to let flavors absorb.',
      'Add pechay leaves and cook for 1 minute.',
      'Serve hot.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/ginataang-tilapia',
    nutrition: { calories: 380, protein: 32, carbs: 6, fat: 25, fiber: 2, sodium: 420 },
  },
  {
    id: 'pancit-canton',
    slug: 'pancit-canton-stir-fry',
    title: 'Classic Pancit Canton',
    summary: 'Stir-fried wheat noodles with pork, shrimp, and colorful vegetables.',
    description:
      'A birthday staple symbolizing long life. Flour sticks (canton noodles) are stir-fried with soy sauce, oyster sauce, pork slices, shrimp, and a medley of vegetables like carrots, beans, and cabbage.',
    heroImage: '/images/recipes/pancit-canton.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '20 mins',
    cookTime: '20 mins',
    totalTime: '40 mins',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviews: 110,
    dietaryTags: [],
    matchIngredients: [
      'canton-noodles',
      'pork-belly',
      'shrimp',
      'carrot',
      'cabbage',
      'green-beans',
      'soy-sauce',
      'oyster-sauce',
    ],
    ingredients: [
      { name: 'Pancit Canton noodles', amount: '500g' },
      { name: 'Pork belly, sliced', amount: '200g' },
      { name: 'Shrimp, shelled', amount: '150g' },
      { name: 'Carrots, julienned', amount: '1 cup' },
      { name: 'Green beans, sliced', amount: '1 cup' },
      { name: 'Cabbage, chopped', amount: '2 cups' },
      { name: 'Soy sauce', amount: '3 tbsp' },
      { name: 'Oyster sauce', amount: '2 tbsp' },
      { name: 'Chicken stock', amount: '3 cups' },
      { name: 'Garlic & Onion', amount: 'minced' },
    ],
    steps: [
      'Sauté garlic and onion. Add pork and cook until brown.',
      'Add shrimp and cook briefly. Remove shrimp and set aside.',
      'Add soy sauce, oyster sauce, and chicken stock. Bring to a boil.',
      'Add vegetables and cook for 2 minutes. Remove veggies and set aside.',
      'Add noodles to the boiling liquid. Cook until liquid is absorbed.',
      'Toss back the meat, shrimp, and vegetables.',
      'Mix well and serve with calamansi.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/pancit-canton',
    nutrition: { calories: 420, protein: 18, carbs: 65, fat: 12, fiber: 4, sodium: 880 },
  },
  {
    id: 'lumpiang-sariwa',
    slug: 'lumpiang-sariwa-fresh-spring-roll',
    title: 'Lumpiang Sariwa (Fresh Spring Roll)',
    summary: 'Fresh vegetable crepe roll with peanut garlic sauce.',
    description:
      'A healthy alternative to fried lumpia. A mix of sautéed vegetables (ubod/heart of palm, carrots, beans) wrapped in a soft homemade crepe, topped with a sweet savory peanut sauce and minced garlic.',
    heroImage: '/images/recipes/lumpiang-sariwa.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '40 mins',
    cookTime: '20 mins',
    totalTime: '1 hr',
    difficulty: 'Advanced',
    rating: 4.7,
    reviews: 58,
    dietaryTags: ['vegetarian-optional', 'high-fiber'],
    matchIngredients: [
      'carrot',
      'green-beans',
      'sweet-potato',
      'cabbage',
      'peanut-butter',
      'garlic',
      'egg',
      'flour',
    ],
    ingredients: [
      { name: 'Ubod (Heart of Palm) or Singkamas, julienned', amount: '2 cups' },
      { name: 'Carrots, julienned', amount: '1 cup' },
      { name: 'Green beans, sliced', amount: '1 cup' },
      { name: 'Sweet potato, cubed', amount: '1 cup' },
      { name: 'Shrimp or Pork (optional)', amount: '150g' },
      { name: 'Lettuce leaves', amount: '6 pcs' },
      { name: 'Wrapper: Flour, egg, water, oil', amount: '1 batch' },
      {
        name: 'Sauce: Soy sauce, sugar, water, cornstarch, peanut butter',
        amount: '1 batch',
      },
    ],
    steps: [
      'Make wrappers: Mix flour, egg, water, oil. Cook thin crepes in a non-stick pan.',
      'Sauté garlic and onion. Add pork/shrimp. Add vegetables and cook until tender-crisp.',
      'Make sauce: Boil water, soy sauce, sugar. Thicken with cornstarch. Stir in peanut butter.',
      'Assemble: Place lettuce on wrapper. Add vegetable filling. Roll and seal.',
      'Pour sauce over the roll.',
      'Garnish with crushed peanuts and minced fresh garlic.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/lumpiang-sariwa',
    nutrition: { calories: 280, protein: 10, carbs: 35, fat: 12, fiber: 6, sodium: 450 },
  },
  {
    id: 'beef-kaldereta-spicy',
    slug: 'beef-kaldereta-spicy-stew',
    title: 'Spicy Beef Kaldereta',
    summary: 'Rich tomato-based beef stew with liver spread, cheese, and chili.',
    description:
      'A popular fiesta dish. Beef chunks are stewed until tender in a thick tomato sauce enriched with liver spread (giving it a distinct savory depth), cheese, bell peppers, olives, and chili.',
    heroImage: '/images/recipes/kaldereta.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '20 mins',
    cookTime: '2 hrs',
    totalTime: '2 hrs 20 mins',
    difficulty: 'Intermediate',
    rating: 4.9,
    reviews: 130,
    dietaryTags: ['high-protein', 'spicy'],
    matchIngredients: [
      'beef-brisket',
      'potato',
      'carrot',
      'bell-pepper',
      'tomato',
      'cheese',
      'chili',
      'liver-spread',
    ],
    ingredients: [
      { name: 'Beef brisket or chuck, cubed', amount: '1 kg' },
      { name: 'Liver spread', amount: '1 small can' },
      { name: 'Tomato sauce', amount: '2 cups' },
      { name: 'Potatoes & Carrots, cubed', amount: '2 cups' },
      { name: 'Bell peppers, sliced', amount: '2 pcs' },
      { name: 'Cheese, grated', amount: '1/2 cup' },
      { name: 'Chili peppers (siling labuyo)', amount: '3 pcs' },
      { name: 'Olives (optional)', amount: '1/4 cup' },
      { name: 'Garlic & Onion', amount: 'minced' },
    ],
    steps: [
      'Sear beef cubes until brown. Set aside.',
      'Sauté garlic and onion. Add beef back.',
      'Add tomato sauce and water. Simmer for 1.5 hours until beef is tender.',
      'Add liver spread and chili. Stir to thicken sauce.',
      'Add potatoes and carrots. Cook until tender.',
      'Add bell peppers, olives, and cheese. Simmer until cheese melts.',
      'Serve hot.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/beef-kaldereta-spicy',
    nutrition: { calories: 520, protein: 38, carbs: 24, fat: 30, fiber: 4, sodium: 920 },
  },
  {
    id: 'ginataang-sitaw-kalabasa',
    slug: 'ginataang-sitaw-kalabasa-veggie',
    title: 'Ginataang Sitaw at Kalabasa',
    summary: 'Squash and string beans simmered in coconut milk with shrimp paste.',
    description:
      'A classic everyday vegetable dish. Sweet squash (kalabasa) and crisp string beans (sitaw) are cooked in coconut milk flavored with shrimp paste (bagoong) and sometimes topped with pork or shrimp.',
    heroImage: '/images/recipes/ginataang-sitaw-kalabasa.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '15 mins',
    cookTime: '20 mins',
    totalTime: '35 mins',
    difficulty: 'Easy',
    rating: 4.7,
    reviews: 55,
    dietaryTags: ['gluten-free'],
    matchIngredients: [
      'squash',
      'string-beans',
      'coconut-milk',
      'shrimp',
      'garlic',
      'onion',
      'shrimp-paste',
    ],
    ingredients: [
      { name: 'Squash (Kalabasa), cubed', amount: '3 cups' },
      { name: 'String beans (Sitaw), cut', amount: '2 cups' },
      { name: 'Coconut milk', amount: '2 cups' },
      { name: 'Pork belly or Shrimp', amount: '150g' },
      { name: 'Shrimp paste (bagoong)', amount: '1 tbsp' },
      { name: 'Garlic & Onion', amount: 'minced' },
      { name: 'Oil', amount: '1 tbsp' },
    ],
    steps: [
      'Sauté garlic and onion. Add pork (if using) and brown.',
      'Add squash and cook for 2 minutes.',
      'Pour in coconut milk. Simmer until squash is half-cooked.',
      'Add string beans and shrimp (if using).',
      'Season with shrimp paste.',
      'Simmer until vegetables are cooked but not mushy.',
      'Serve hot.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/ginataang-sitaw-kalabasa',
    nutrition: { calories: 280, protein: 12, carbs: 22, fat: 18, fiber: 6, sodium: 580 },
  },
  {
    id: 'pork-barbecue',
    slug: 'pork-barbecue-skewers',
    title: 'Filipino Pork Barbecue',
    summary: 'Sweet and savory grilled pork skewers, a street food favorite.',
    description:
      'Thin slices of pork marinated in a sweet soy-ketchup-calamansi mixture, skewered on bamboo sticks, and grilled over charcoal. The glaze caramelizes into a sticky, smoky, delicious coating.',
    heroImage: '/images/recipes/pork-bbq.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '30 mins',
    cookTime: '20 mins',
    totalTime: '50 mins',
    difficulty: 'Intermediate',
    rating: 4.9,
    reviews: 140,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'pork-shoulder',
      'soy-sauce',
      'banana-ketchup',
      'calamansi',
      'garlic',
      'sugar',
      'lemon-soda',
    ],
    ingredients: [
      { name: 'Pork shoulder (kasim), sliced thinly', amount: '1 kg' },
      { name: 'Soy sauce', amount: '1/2 cup' },
      { name: 'Banana ketchup', amount: '1/2 cup' },
      { name: 'Calamansi juice', amount: '1/4 cup' },
      { name: 'Brown sugar', amount: '1/2 cup' },
      { name: 'Garlic, minced', amount: '1 head' },
      { name: 'Lemon soda (Sprite/7Up)', amount: '1/2 cup' },
      { name: 'Black pepper', amount: '1 tsp' },
      { name: 'Bamboo skewers (soaked in water)', amount: '20 pcs' },
    ],
    steps: [
      'Mix all marinade ingredients in a bowl.',
      'Marinate pork slices overnight for best results.',
      'Thread pork onto bamboo skewers.',
      'Grill over charcoal, turning frequently.',
      'Baste with the remaining marinade (boiled) mixed with a little oil.',
      'Cook until charred and glazed.',
      'Serve with spiced vinegar.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/pork-barbecue',
    nutrition: { calories: 320, protein: 25, carbs: 15, fat: 18, fiber: 0, sodium: 750 },
  },
  {
    id: 'ginataang-mais',
    slug: 'ginataang-mais-corn-pudding',
    title: 'Ginataang Mais',
    summary: 'Sweet rice porridge with corn kernels and coconut milk.',
    description:
      'A simple afternoon snack (merienda). Glutinous rice is cooked with water, coconut milk, sugar, and corn kernels until thick and creamy. Comforting served warm or cold.',
    heroImage: '/images/recipes/ginataang-mais.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '5 mins',
    cookTime: '30 mins',
    totalTime: '35 mins',
    difficulty: 'Easy',
    rating: 4.7,
    reviews: 50,
    dietaryTags: ['vegetarian', 'gluten-free', 'sweet'],
    matchIngredients: ['glutinous-rice', 'corn', 'coconut-milk', 'sugar'],
    ingredients: [
      { name: 'Glutinous rice (malagkit)', amount: '1 cup' },
      { name: 'Coconut milk', amount: '4 cups' },
      { name: 'Whole corn kernels', amount: '1 cup' },
      { name: 'Sugar', amount: '1/2 cup' },
      { name: 'Water', amount: '1 cup' },
      { name: 'Salt', amount: 'pinch' },
    ],
    steps: [
      'Wash glutinous rice.',
      'In a pot, combine rice, water, and coconut milk.',
      'Bring to a boil, then lower heat to simmer.',
      'Stir occasionally to prevent sticking.',
      'When rice is almost cooked, add corn and sugar.',
      'Simmer until rice is soft and mixture is thick.',
      'Serve warm.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/ginataang-mais',
    nutrition: { calories: 280, protein: 4, carbs: 55, fat: 8, fiber: 2, sodium: 80 },
  },
  {
    id: 'adobong-sitaw',
    slug: 'adobong-sitaw-string-beans',
    title: 'Adobong Sitaw',
    summary: 'String beans cooked adobo-style with pork bits.',
    description:
      'Crunchy string beans (sitaw) braised in the classic soy sauce and vinegar mixture. Usually cooked with small pieces of pork belly for flavor.',
    heroImage: '/images/recipes/adobong-sitaw.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '10 mins',
    cookTime: '20 mins',
    totalTime: '30 mins',
    difficulty: 'Easy',
    rating: 4.6,
    reviews: 45,
    dietaryTags: ['high-fiber'],
    matchIngredients: [
      'string-beans',
      'pork-belly',
      'soy-sauce',
      'vinegar',
      'garlic',
      'onion',
    ],
    ingredients: [
      { name: 'String beans (Sitaw), cut into 2-inch lengths', amount: '1 bundle' },
      { name: 'Pork belly, sliced thinly', amount: '150g' },
      { name: 'Soy sauce', amount: '1/4 cup' },
      { name: 'Vinegar', amount: '2 tbsp' },
      { name: 'Garlic, minced', amount: '4 cloves' },
      { name: 'Onion, chopped', amount: '1 small' },
      { name: 'Water', amount: '1/4 cup' },
      { name: 'Oil', amount: '1 tbsp' },
    ],
    steps: [
      'Sauté garlic and onion.',
      'Add pork and cook until brown.',
      'Add soy sauce and water. Simmer for 5 minutes.',
      'Add string beans. Cook until tender-crisp.',
      'Add vinegar and let simmer for a minute without stirring.',
      'Toss well and serve.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/adobong-sitaw',
    nutrition: { calories: 180, protein: 10, carbs: 12, fat: 12, fiber: 4, sodium: 550 },
  },
  {
    id: 'fish-tinola',
    slug: 'fish-tinola-soup',
    title: 'Fish Tinola',
    summary: 'Clear fish soup with ginger, leafy greens, and sayote.',
    description:
      'A lighter variation of Chicken Tinola using fresh fish (like Tuna or Lapu-Lapu). The broth is flavored with ginger and onions, served with sayote or papaya and malunggay or chili leaves.',
    heroImage: '/images/recipes/fish-tinola.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '15 mins',
    cookTime: '20 mins',
    totalTime: '35 mins',
    difficulty: 'Easy',
    rating: 4.5,
    reviews: 35,
    dietaryTags: ['pescetarian', 'low-calorie'],
    matchIngredients: ['fish-fillet', 'ginger', 'sayote', 'malunggay', 'onion', 'garlic'],
    ingredients: [
      { name: 'Fish (Tuna or White Fish), sliced', amount: '500g' },
      { name: 'Ginger, sliced', amount: '1 thumb-sized' },
      { name: 'Sayote or Green Papaya, wedges', amount: '1 pc' },
      { name: 'Malunggay or Chili leaves', amount: '1 cup' },
      { name: 'Onion, chopped', amount: '1 medium' },
      { name: 'Water or Rice wash', amount: '4 cups' },
      { name: 'Fish sauce', amount: '1 tbsp' },
    ],
    steps: [
      'Boil water/rice wash with ginger and onion.',
      'Add sayote/papaya. Cook until half-tender.',
      "Add fish slices. Simmer gently so fish doesn't break.",
      'Season with fish sauce.',
      'Add leafy greens and turn off heat.',
      'Serve hot.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/fish-tinola',
    nutrition: { calories: 180, protein: 25, carbs: 8, fat: 4, fiber: 3, sodium: 420 },
  },
  {
    id: 'tortang-dulong',
    slug: 'tortang-dulong-fish-omelet',
    title: 'Tortang Dulong',
    summary: 'Silver fish omelet patties, crispy on the outside and soft inside.',
    description:
      'Tiny silver fish (dulong) mixed with egg, flour, and spices, then pan-fried into patties. A delicious breakfast or side dish, often dipped in ketchup or vinegar.',
    heroImage: '/images/recipes/tortang-dulong.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '10 mins',
    cookTime: '15 mins',
    totalTime: '25 mins',
    difficulty: 'Easy',
    rating: 4.6,
    reviews: 40,
    dietaryTags: ['pescetarian', 'high-protein'],
    matchIngredients: ['fish-fillet', 'egg', 'flour', 'garlic', 'onion', 'scallions'],
    ingredients: [
      { name: 'Dulong (Silver fish), washed and drained', amount: '2 cups' },
      { name: 'Eggs, beaten', amount: '3 pcs' },
      { name: 'Flour', amount: '1/2 cup' },
      { name: 'Garlic, minced', amount: '3 cloves' },
      { name: 'Onion, minced', amount: '1 small' },
      { name: 'Spring onions, chopped', amount: '2 tbsp' },
      { name: 'Salt and pepper', amount: 'to taste' },
      { name: 'Oil', amount: 'for frying' },
    ],
    steps: [
      'In a bowl, mix dulong, eggs, flour, garlic, onion, spring onions, salt, and pepper.',
      'Heat oil in a pan.',
      'Scoop spoonfuls of the mixture into the pan.',
      'Fry until golden brown on both sides.',
      'Drain on paper towels.',
      'Serve with vinegar or ketchup.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/tortang-dulong',
    nutrition: { calories: 220, protein: 18, carbs: 12, fat: 10, fiber: 1, sodium: 350 },
  },
];

// Read existing recipes
let existingRecipes = [];
try {
  const data = fs.readFileSync(RECIPES_PATH, 'utf8');
  existingRecipes = JSON.parse(data);
} catch (err) {
  console.error('Error reading recipes.json:', err);
  process.exit(1);
}

console.log(`Current recipe count: ${existingRecipes.length}`);

// Merge recipes
let addedCount = 0;
newRecipes.forEach((newRecipe) => {
  const exists = existingRecipes.some(
    (r) => r.id === newRecipe.id || r.slug === newRecipe.slug
  );

  if (!exists) {
    existingRecipes.push(newRecipe);
    addedCount++;
    console.log(`Added: ${newRecipe.title}`);
  } else {
    console.log(`Skipped (Duplicate): ${newRecipe.title}`);
  }
});

// Write back to file
try {
  fs.writeFileSync(RECIPES_PATH, JSON.stringify(existingRecipes, null, 2), 'utf8');
  console.log(`\nSuccess! Added ${addedCount} new recipes.`);
  console.log(`Total recipes now: ${existingRecipes.length}`);
} catch (err) {
  console.error('Error writing recipes.json:', err);
}
