const fs = require('fs');
const path = require('path');

const RECIPES_PATH = path.join(__dirname, '../data/recipes.json');

// Batch 3: Final 20 Authentic Filipino Recipes to reach 100+
const newRecipes = [
  {
    id: 'bicol-express',
    slug: 'bicol-express-spicy',
    title: 'Bicol Express',
    summary: 'Spicy pork stew simmered in coconut milk with lots of chili peppers.',
    description:
      'A fiery dish from the Bicol region. Pork belly cubes are cooked in rich coconut milk (gata) with plenty of shrimp paste (bagoong) and chili peppers (siling labuyo and siling haba).',
    heroImage: '/images/recipes/bicol-express.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '15 mins',
    cookTime: '40 mins',
    totalTime: '55 mins',
    difficulty: 'Intermediate',
    rating: 4.9,
    reviews: 115,
    dietaryTags: ['spicy', 'high-fat'],
    matchIngredients: [
      'pork-belly',
      'coconut-milk',
      'chili',
      'shrimp-paste',
      'garlic',
      'onion',
      'ginger',
    ],
    ingredients: [
      { name: 'Pork belly, cubed', amount: '500g' },
      { name: 'Coconut milk', amount: '2 cups' },
      { name: 'Coconut cream (kakang gata)', amount: '1 cup' },
      { name: 'Shrimp paste (bagoong alamang)', amount: '2 tbsp' },
      { name: 'Green chilies (siling haba), sliced', amount: '1 cup' },
      { name: 'Red chilies (siling labuyo), minced', amount: '5 pcs' },
      { name: 'Garlic, minced', amount: '4 cloves' },
      { name: 'Onion, chopped', amount: '1 medium' },
      { name: 'Ginger, minced', amount: '1 tbsp' },
    ],
    steps: [
      'Sauté garlic, onion, and ginger.',
      'Add pork belly and cook until lightly browned.',
      'Add shrimp paste and cook for a minute.',
      'Pour in coconut milk. Simmer until pork is tender and sauce reduces.',
      'Add the chilies.',
      'Pour in coconut cream. Simmer until oil separates and sauce is thick.',
      'Serve hot with plenty of rice.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/bicol-express',
    nutrition: { calories: 550, protein: 25, carbs: 8, fat: 45, fiber: 2, sodium: 800 },
  },
  {
    id: 'dinuguan',
    slug: 'dinuguan-pork-blood-stew',
    title: 'Dinuguan (Chocolate Meat)',
    summary: "Savory pork stew cooked in pig's blood, vinegar, and spices.",
    description:
      "A classic Filipino stew made from pork meat and offal simmered in a rich, dark gravy of pig's blood, garlic, chili, and vinegar. Often called 'Chocolate Meat' due to its color.",
    heroImage: '/images/recipes/dinuguan.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '30 mins',
    cookTime: '1 hr',
    totalTime: '1 hr 30 mins',
    difficulty: 'Advanced',
    rating: 4.7,
    reviews: 95,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'pork-belly',
      'pork-blood',
      'vinegar',
      'garlic',
      'onion',
      'chili',
      'ginger',
    ],
    ingredients: [
      { name: 'Pork belly, cubed', amount: '500g' },
      { name: 'Pork intestines/ears (optional)', amount: '200g' },
      { name: "Pig's blood", amount: '2 cups' },
      { name: 'Vinegar', amount: '1/2 cup' },
      { name: 'Garlic, minced', amount: '1 head' },
      { name: 'Onion, chopped', amount: '1 large' },
      { name: 'Green chilies (siling haba)', amount: '3 pcs' },
      { name: 'Bay leaves', amount: '2 pcs' },
      { name: 'Sugar', amount: '1 tbsp' },
      { name: 'Water', amount: '1 cup' },
    ],
    steps: [
      'Sauté garlic and onion. Add pork and cook until brown.',
      'Add vinegar and bring to a boil without stirring.',
      'Add water and bay leaves. Simmer until pork is tender.',
      "Add pig's blood (strain it first) while stirring continuously to prevent lumps.",
      'Simmer for 15 minutes until sauce thickens.',
      'Add green chilies and sugar. Season with salt and pepper.',
      'Serve with Puto (rice cake).',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/dinuguan',
    nutrition: { calories: 380, protein: 35, carbs: 6, fat: 24, fiber: 1, sodium: 650 },
  },
  {
    id: 'arroz-caldo',
    slug: 'arroz-caldo-chicken-porridge',
    title: 'Arroz Caldo',
    summary: 'Comforting chicken rice porridge flavored with ginger and toasted garlic.',
    description:
      'The ultimate Filipino comfort food. Glutinous rice is cooked with chicken, ginger, and garlic until it forms a thick porridge. Topped with toasted garlic, spring onions, and a squeeze of calamansi.',
    heroImage: '/images/recipes/arroz-caldo.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '15 mins',
    cookTime: '45 mins',
    totalTime: '1 hr',
    difficulty: 'Easy',
    rating: 4.8,
    reviews: 120,
    dietaryTags: ['gluten-free'],
    matchIngredients: [
      'chicken-thigh',
      'glutinous-rice',
      'ginger',
      'garlic',
      'onion',
      'safflower',
      'egg',
      'calamansi',
    ],
    ingredients: [
      { name: 'Chicken thighs/wings', amount: '500g' },
      { name: 'Glutinous rice', amount: '1 cup' },
      { name: 'Ginger, julienned', amount: '2 tbsp' },
      { name: 'Garlic, minced', amount: '1 head' },
      { name: 'Onion, chopped', amount: '1 small' },
      { name: 'Chicken stock/water', amount: '6 cups' },
      { name: 'Kasubha (safflower) or Saffron', amount: 'pinch' },
      { name: 'Fish sauce', amount: '2 tbsp' },
      { name: 'Boiled eggs', amount: '4 pcs' },
      { name: 'Spring onions', amount: 'garnish' },
    ],
    steps: [
      'Fry half the garlic until golden brown. Set aside for topping.',
      'In the same pot, sauté onion, ginger, and remaining garlic.',
      'Add chicken and brown slightly.',
      'Add glutinous rice and stir for a minute.',
      'Pour in chicken stock. Bring to a boil then simmer.',
      'Stir occasionally. Cook until rice is soft and porridge is thick (about 30-40 mins).',
      'Add kasubha and fish sauce.',
      'Serve topped with boiled egg, toasted garlic, and spring onions.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/arroz-caldo',
    nutrition: { calories: 350, protein: 20, carbs: 45, fat: 10, fiber: 2, sodium: 700 },
  },
  {
    id: 'champorado',
    slug: 'champorado-chocolate-rice',
    title: 'Champorado',
    summary: 'Sweet chocolate rice porridge, perfect for breakfast or rainy days.',
    description:
      'A sweet porridge made with glutinous rice and cocoa powder or tablea (pure chocolate tablets). Traditionally served with tuyo (dried salted fish) to balance the sweetness.',
    heroImage: '/images/recipes/champorado.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '5 mins',
    cookTime: '30 mins',
    totalTime: '35 mins',
    difficulty: 'Easy',
    rating: 4.9,
    reviews: 105,
    dietaryTags: ['vegetarian', 'sweet'],
    matchIngredients: ['glutinous-rice', 'cocoa-powder', 'sugar', 'milk', 'dried-fish'],
    ingredients: [
      { name: 'Glutinous rice', amount: '1 cup' },
      { name: 'Tablea (cacao tablets) or Cocoa powder', amount: '5 pcs / 1/2 cup' },
      { name: 'Sugar', amount: '1/2 cup' },
      { name: 'Water', amount: '4 cups' },
      { name: 'Evaporated milk or Condensed milk', amount: 'drizzle' },
      { name: 'Tuyo (dried fish)', amount: 'optional side' },
    ],
    steps: [
      'Boil water in a pot.',
      'Add glutinous rice and stir. Simmer until rice is half-cooked.',
      'Add tablea or cocoa powder. Stir until dissolved.',
      'Add sugar. Continue simmering until rice is fully cooked and texture is thick.',
      'Serve hot with a swirl of evaporated milk.',
      'Pair with fried tuyo for the classic combo.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/champorado',
    nutrition: { calories: 320, protein: 6, carbs: 60, fat: 5, fiber: 4, sodium: 50 },
  },
  {
    id: 'turon',
    slug: 'turon-banana-lumpia',
    title: 'Turon (Banana Lumpia)',
    summary: 'Deep-fried banana rolls with jackfruit and caramelized sugar.',
    description:
      'A favorite merienda. Saba bananas and strips of jackfruit (langka) are rolled in spring roll wrappers, dusted with brown sugar, and deep-fried until golden and caramelized.',
    heroImage: '/images/recipes/turon.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '15 mins',
    cookTime: '15 mins',
    totalTime: '30 mins',
    difficulty: 'Easy',
    rating: 4.9,
    reviews: 150,
    dietaryTags: ['vegetarian', 'vegan', 'sweet'],
    matchIngredients: [
      'banana-saba',
      'jackfruit',
      'lumpia-wrapper',
      'brown-sugar',
      'oil',
    ],
    ingredients: [
      { name: 'Saba bananas, halved lengthwise', amount: '6 pcs' },
      { name: 'Jackfruit (Langka), strips', amount: '1/2 cup' },
      { name: 'Lumpia wrappers', amount: '12 pcs' },
      { name: 'Brown sugar', amount: '1 cup' },
      { name: 'Oil', amount: 'for frying' },
    ],
    steps: [
      'Roll banana slices in brown sugar.',
      'Place a banana slice and some jackfruit on a wrapper.',
      'Roll tightly and seal edges with water.',
      'Heat oil in a pan.',
      'Sprinkle some brown sugar into the hot oil (to caramelize and coat the wrapper).',
      'Fry the rolls until golden brown and glazed.',
      'Drain slightly and serve warm.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/turon',
    nutrition: { calories: 250, protein: 2, carbs: 45, fat: 8, fiber: 3, sodium: 80 },
  },
  {
    id: 'tokwat-baboy',
    slug: 'tokwat-baboy-appetizer',
    title: "Tokwa't Baboy",
    summary: 'Fried tofu and boiled pork ears in a soy-vinegar dressing.',
    description:
      'A classic appetizer or side dish for lugaw/congee. Cubes of fried tofu and tender pork (ears or belly) are tossed in a mixture of soy sauce, vinegar, chopped onions, and chili.',
    heroImage: '/images/recipes/tokwat-baboy.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '10 mins',
    cookTime: '30 mins',
    totalTime: '40 mins',
    difficulty: 'Easy',
    rating: 4.7,
    reviews: 70,
    dietaryTags: ['high-protein'],
    matchIngredients: ['tofu', 'pork-belly', 'soy-sauce', 'vinegar', 'onion', 'chili'],
    ingredients: [
      { name: 'Firm tofu, cubed and fried', amount: '2 blocks' },
      { name: 'Pork belly or ears, boiled and cubed', amount: '300g' },
      { name: 'Soy sauce', amount: '1/2 cup' },
      { name: 'Vinegar', amount: '1/2 cup' },
      { name: 'Onion, chopped', amount: '1 large' },
      { name: 'Green chili, chopped', amount: '2 pcs' },
      { name: 'Sugar', amount: '1 tsp' },
    ],
    steps: [
      'Fry tofu until golden and crispy. Set aside.',
      'Boil pork until tender. Slice into cubes.',
      'In a bowl, mix soy sauce, vinegar, sugar, onions, and chili.',
      'Combine fried tofu and pork in a serving dish.',
      'Pour the sauce over the mixture.',
      'Serve as pulutan or side dish.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/tokwat-baboy',
    nutrition: { calories: 320, protein: 22, carbs: 8, fat: 22, fiber: 2, sodium: 650 },
  },
  {
    id: 'pancit-palabok',
    slug: 'pancit-palabok-noodles',
    title: 'Pancit Palabok',
    summary: 'Rice noodles topped with a golden shrimp sauce, chicharon, and eggs.',
    description:
      'A festive noodle dish. Thin rice noodles are smothered in a thick, savory orange sauce made from shrimp juice and annatto, then topped with crushed chicharon, tinapa flakes, shrimp, eggs, and spring onions.',
    heroImage: '/images/recipes/pancit-palabok.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 8,
    prepTime: '30 mins',
    cookTime: '30 mins',
    totalTime: '1 hr',
    difficulty: 'Advanced',
    rating: 4.8,
    reviews: 90,
    dietaryTags: [],
    matchIngredients: [
      'rice-noodles',
      'shrimp',
      'tinapa',
      'chicharon',
      'egg',
      'annatto',
      'cornstarch',
    ],
    ingredients: [
      { name: 'Rice noodles (bihon), soaked', amount: '500g' },
      { name: 'Shrimp, shelled (save heads for juice)', amount: '200g' },
      { name: 'Tinapa (smoked fish) flakes', amount: '1/2 cup' },
      { name: 'Chicharon, crushed', amount: '1 cup' },
      { name: 'Boiled eggs, sliced', amount: '3 pcs' },
      { name: 'Annatto water', amount: '1/2 cup' },
      { name: 'Cornstarch', amount: '3 tbsp' },
      { name: 'Shrimp juice (from heads)', amount: '2 cups' },
      { name: 'Spring onions & Fried garlic', amount: 'garnish' },
    ],
    steps: [
      'Boil noodles until cooked. Drain and place on a platter.',
      'Make sauce: Sauté garlic and onions. Add shrimp juice and annatto water. Bring to a boil.',
      'Thicken sauce with cornstarch dissolved in water. Season with salt and pepper.',
      'Pour sauce over noodles.',
      'Top with shrimp, tinapa flakes, chicharon, eggs, garlic, and spring onions.',
      'Serve with calamansi.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/pancit-palabok',
    nutrition: { calories: 450, protein: 20, carbs: 65, fat: 15, fiber: 2, sodium: 850 },
  },
  {
    id: 'embutido',
    slug: 'embutido-filipino-meatloaf',
    title: 'Embutido',
    summary: 'Filipino-style steamed meatloaf wrapped in foil.',
    description:
      'A special occasion dish. Ground pork is mixed with raisins, carrots, pickles, cheese, and sausages, wrapped around hard-boiled eggs and sausages, then steamed. Can be served warm or fried.',
    heroImage: '/images/recipes/embutido.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 8,
    prepTime: '30 mins',
    cookTime: '1 hr',
    totalTime: '1 hr 30 mins',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 65,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'ground-pork',
      'carrot',
      'raisins',
      'pickle-relish',
      'cheese',
      'egg',
      'sausage',
    ],
    ingredients: [
      { name: 'Ground pork', amount: '1 kg' },
      { name: 'Carrots, minced', amount: '1 cup' },
      { name: 'Raisins', amount: '1/2 cup' },
      { name: 'Pickle relish', amount: '1/2 cup' },
      { name: 'Cheese, grated', amount: '1/2 cup' },
      { name: 'Eggs, raw', amount: '2 pcs' },
      { name: 'Breadcrumbs', amount: '1 cup' },
      { name: 'Hard-boiled eggs, sliced', amount: '3 pcs' },
      { name: 'Vienna sausage or Hotdogs', amount: '4 pcs' },
      { name: 'Aluminum foil', amount: 'for wrapping' },
    ],
    steps: [
      'Mix ground pork, carrots, raisins, relish, cheese, raw eggs, breadcrumbs, salt, and pepper.',
      'Spread mixture on a sheet of foil.',
      'Place sausage and boiled egg slices in the center.',
      'Roll the foil tightly into a log, sealing the ends.',
      'Steam for 1 hour.',
      'Let cool. Slice and serve, or fry slices before serving.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/embutido',
    nutrition: { calories: 320, protein: 25, carbs: 12, fat: 20, fiber: 1, sodium: 600 },
  },
  {
    id: 'sinampalukang-manok',
    slug: 'sinampalukang-manok-tamarind',
    title: 'Sinampalukang Manok',
    summary: 'Chicken soup soured with young tamarind leaves and fruit.',
    description:
      'Similar to Sinigang but uses chicken and is traditionally soured with young tamarind leaves and flowers, giving it a distinct herbal sourness. The chicken is sautéed in ginger first for better flavor.',
    heroImage: '/images/recipes/sinampalukang-manok.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 5,
    prepTime: '20 mins',
    cookTime: '45 mins',
    totalTime: '1 hr 5 mins',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviews: 50,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'chicken-thigh',
      'tamarind-leaves',
      'ginger',
      'onion',
      'garlic',
      'string-beans',
      'eggplant',
    ],
    ingredients: [
      { name: 'Chicken, cut into serving pieces', amount: '1 kg' },
      { name: 'Young tamarind leaves/flowers', amount: '2 cups' },
      { name: 'Unripe tamarind fruit (optional)', amount: '5 pcs' },
      { name: 'Ginger, sliced', amount: '1 thumb-sized' },
      { name: 'Garlic & Onion', amount: 'minced' },
      { name: 'String beans & Eggplant', amount: '1 cup each' },
      { name: 'Fish sauce', amount: '2 tbsp' },
    ],
    steps: [
      'Sauté ginger, garlic, and onion.',
      'Add chicken and cook until lightly browned.',
      'Add fish sauce and cook for another minute.',
      'Add water and tamarind fruit. Simmer until chicken is tender.',
      'Mash the tamarind fruit to release flavor.',
      'Add tamarind leaves and vegetables.',
      'Simmer until vegetables are cooked.',
      'Serve hot.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/sinampalukang-manok',
    nutrition: { calories: 280, protein: 30, carbs: 8, fat: 12, fiber: 3, sodium: 750 },
  },
  {
    id: 'inihaw-na-liempo',
    slug: 'inihaw-na-liempo-grilled-belly',
    title: 'Inihaw na Liempo',
    summary: 'Marinated grilled pork belly served with spicy vinegar.',
    description:
      'Juicy pork belly strips marinated in soy sauce, calamansi, garlic, and pepper, then grilled over charcoal until smoky and tender. The fat renders down to a crispy, flavorful delight.',
    heroImage: '/images/recipes/inihaw-na-liempo.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '10 mins',
    cookTime: '20 mins',
    totalTime: '30 mins',
    difficulty: 'Easy',
    rating: 4.9,
    reviews: 135,
    dietaryTags: ['high-fat', 'keto-friendly'],
    matchIngredients: [
      'pork-belly',
      'soy-sauce',
      'calamansi',
      'garlic',
      'pepper',
      'vinegar',
    ],
    ingredients: [
      { name: 'Pork belly, sliced 1/2 inch thick', amount: '1 kg' },
      { name: 'Soy sauce', amount: '1/2 cup' },
      { name: 'Calamansi juice', amount: '1/4 cup' },
      { name: 'Garlic, minced', amount: '1 head' },
      { name: 'Black pepper', amount: '1 tsp' },
      { name: 'Oil', amount: '2 tbsp' },
      { name: 'Spiced vinegar (dip)', amount: '1/2 cup' },
    ],
    steps: [
      'Combine soy sauce, calamansi, garlic, pepper, and oil.',
      'Marinate pork belly for at least 3 hours.',
      'Grill over charcoal or in a grill pan.',
      'Cook for 5-7 minutes per side until cooked through and charred.',
      'Let rest for 5 minutes before slicing.',
      'Serve with spiced vinegar and rice.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/inihaw-na-liempo',
    nutrition: { calories: 550, protein: 20, carbs: 4, fat: 50, fiber: 0, sodium: 600 },
  },
  {
    id: 'bibingka',
    slug: 'bibingka-rice-cake',
    title: 'Bibingka',
    summary: 'Traditional rice cake cooked in banana leaves with salted egg and cheese.',
    description:
      'A Christmas favorite. Rice flour batter is poured into banana leaf-lined clay pots and baked with coals on top and bottom. Topped with salted egg slices, cheese, and grated coconut.',
    heroImage: '/images/recipes/bibingka.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '20 mins',
    cookTime: '20 mins',
    totalTime: '40 mins',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviews: 80,
    dietaryTags: ['vegetarian', 'gluten-free'],
    matchIngredients: [
      'rice-flour',
      'coconut-milk',
      'egg',
      'sugar',
      'cheese',
      'salted-egg',
      'butter',
    ],
    ingredients: [
      { name: 'Rice flour', amount: '2 cups' },
      { name: 'Coconut milk', amount: '1 cup' },
      { name: 'Water', amount: '1/2 cup' },
      { name: 'Eggs', amount: '3 pcs' },
      { name: 'Sugar', amount: '1/2 cup' },
      { name: 'Baking powder', amount: '1 tbsp' },
      { name: 'Salted egg, sliced', amount: '1 pc' },
      { name: 'Cheese, sliced', amount: '1/4 cup' },
      { name: 'Butter', amount: 'topping' },
      { name: 'Grated coconut', amount: 'topping' },
    ],
    steps: [
      'Whisk eggs and sugar until creamy.',
      'Add rice flour, baking powder, coconut milk, and water. Mix until smooth.',
      'Line molds with banana leaves.',
      'Pour batter into molds.',
      'Top with salted egg and cheese.',
      'Bake in oven at 375°F (190°C) for 20-25 minutes.',
      'Brush with butter and top with grated coconut.',
      'Serve warm.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/bibingka',
    nutrition: { calories: 350, protein: 8, carbs: 55, fat: 12, fiber: 2, sodium: 250 },
  },
  {
    id: 'puto-bumbong',
    slug: 'puto-bumbong-purple-rice',
    title: 'Puto Bumbong',
    summary: 'Steamed purple rice cake served with butter, sugar, and coconut.',
    description:
      'Another Simbang Gabi staple. Made from purple glutinous rice (pirurutong) steamed in bamboo tubes. Served with margarine or butter, muscovado sugar, and grated coconut.',
    heroImage: '/images/recipes/puto-bumbong.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '6 hrs (soaking)',
    cookTime: '10 mins',
    totalTime: '6 hrs 10 mins',
    difficulty: 'Advanced',
    rating: 4.9,
    reviews: 75,
    dietaryTags: ['vegetarian', 'gluten-free'],
    matchIngredients: [
      'glutinous-rice',
      'purple-yam-powder',
      'butter',
      'muscovado-sugar',
      'coconut',
    ],
    ingredients: [
      { name: 'Glutinous rice', amount: '1 cup' },
      { name: 'Purple rice (Pirurutong) or Food color', amount: '1/2 cup' },
      { name: 'Water', amount: 'for soaking' },
      { name: 'Butter or Margarine', amount: 'topping' },
      { name: 'Muscovado sugar', amount: 'topping' },
      { name: 'Grated coconut', amount: 'topping' },
    ],
    steps: [
      'Soak rice mixture overnight. Grind slightly to make coarse flour.',
      'Wrap in cloth and drain excess water.',
      'Fill bamboo tubes (bumbong) with the mixture.',
      'Steam for a few minutes until cooked.',
      'Push out of the tube.',
      'Spread butter, sprinkle sugar and coconut.',
      'Serve hot.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/puto-bumbong',
    nutrition: { calories: 280, protein: 4, carbs: 50, fat: 8, fiber: 2, sodium: 50 },
  },
  {
    id: 'banana-cue',
    slug: 'banana-cue-snack',
    title: 'Banana Cue',
    summary: 'Deep-fried saba bananas coated in caramelized brown sugar.',
    description:
      'The quintessential Filipino street food. Saba bananas are deep-fried, then brown sugar is added to the oil to caramelize and coat the bananas. Skewered on bamboo sticks.',
    heroImage: '/images/recipes/banana-cue.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '5 mins',
    cookTime: '15 mins',
    totalTime: '20 mins',
    difficulty: 'Easy',
    rating: 4.8,
    reviews: 100,
    dietaryTags: ['vegan', 'vegetarian', 'sweet'],
    matchIngredients: ['banana-saba', 'brown-sugar', 'oil'],
    ingredients: [
      { name: 'Saba bananas', amount: '8 pcs' },
      { name: 'Brown sugar', amount: '1 cup' },
      { name: 'Oil', amount: 'for deep frying' },
    ],
    steps: [
      'Heat oil in a deep pan.',
      'Add bananas and fry for 2 minutes.',
      'Sprinkle brown sugar into the oil.',
      'Wait for sugar to melt and float.',
      'Stir bananas to coat them in the caramelized sugar.',
      'Remove and drain slightly.',
      'Skewer on bamboo sticks (2 per stick).',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/banana-cue',
    nutrition: { calories: 220, protein: 1, carbs: 45, fat: 6, fiber: 3, sodium: 10 },
  },
  {
    id: 'taho-homemade',
    slug: 'taho-homemade-tofu',
    title: 'Homemade Taho',
    summary: 'Silken tofu with sweet syrup and sago pearls.',
    description:
      'A beloved morning snack usually sold by peddlers. Soft silken tofu is topped with arnibal (brown sugar syrup) and sago pearls. This recipe uses store-bought silken tofu for an easy homemade version.',
    heroImage: '/images/recipes/taho.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '10 mins',
    cookTime: '20 mins',
    totalTime: '30 mins',
    difficulty: 'Easy',
    rating: 4.9,
    reviews: 85,
    dietaryTags: ['vegan', 'vegetarian', 'sweet', 'high-protein'],
    matchIngredients: ['tofu', 'brown-sugar', 'sago', 'vanilla'],
    ingredients: [
      { name: 'Silken tofu', amount: '1 block (500g)' },
      { name: 'Brown sugar', amount: '1 cup' },
      { name: 'Water', amount: '1 cup' },
      { name: 'Sago pearls, cooked', amount: '1 cup' },
      { name: 'Vanilla extract', amount: '1 tsp' },
    ],
    steps: [
      'Make syrup (Arnibal): Boil water, brown sugar, and vanilla until slightly thick.',
      'Steam silken tofu for 10-15 minutes to heat through.',
      'Scoop thin layers of tofu into a cup.',
      'Add cooked sago pearls.',
      'Pour hot syrup over the tofu.',
      'Mix and enjoy warm.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/taho-homemade',
    nutrition: { calories: 180, protein: 8, carbs: 35, fat: 2, fiber: 1, sodium: 10 },
  },
  {
    id: 'kwek-kwek',
    slug: 'kwek-kwek-street-food',
    title: 'Kwek-Kwek',
    summary: 'Boiled quail eggs coated in orange batter and deep-fried.',
    description:
      'A popular street food. Hard-boiled quail eggs are dipped in an orange-colored batter (flour, cornstarch, annatto) and deep-fried until crispy. Served with vinegar or sweet sauce.',
    heroImage: '/images/recipes/kwek-kwek.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 4,
    prepTime: '20 mins',
    cookTime: '15 mins',
    totalTime: '35 mins',
    difficulty: 'Easy',
    rating: 4.8,
    reviews: 110,
    dietaryTags: ['vegetarian'],
    matchIngredients: ['quail-eggs', 'flour', 'cornstarch', 'annatto', 'baking-powder'],
    ingredients: [
      { name: 'Quail eggs, boiled and peeled', amount: '24 pcs' },
      { name: 'Flour', amount: '1 cup' },
      { name: 'Cornstarch', amount: '1/4 cup' },
      { name: 'Baking powder', amount: '1 tsp' },
      { name: 'Annatto powder (for color)', amount: '1 tsp' },
      { name: 'Water', amount: '3/4 cup' },
      { name: 'Salt and pepper', amount: 'pinch' },
      { name: 'Oil', amount: 'for frying' },
    ],
    steps: [
      'Mix flour, cornstarch, baking powder, annatto, salt, pepper, and water to make a smooth batter.',
      'Dredge quail eggs in a little flour.',
      'Dip eggs into the batter.',
      'Deep fry until crispy and orange.',
      'Drain on paper towels.',
      'Serve with spiced vinegar.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/kwek-kwek',
    nutrition: { calories: 250, protein: 10, carbs: 25, fat: 12, fiber: 1, sodium: 300 },
  },
  {
    id: 'pancit-malabon',
    slug: 'pancit-malabon-seafood',
    title: 'Pancit Malabon',
    summary: 'Thick rice noodles with seafood sauce, oysters, and squid.',
    description:
      "Similar to Palabok but uses thicker noodles and the sauce is mixed in, not poured on top. Loaded with seafood like oysters, squid, and shrimp, reflecting Malabon's fishing heritage.",
    heroImage: '/images/recipes/pancit-malabon.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 8,
    prepTime: '30 mins',
    cookTime: '30 mins',
    totalTime: '1 hr',
    difficulty: 'Advanced',
    rating: 4.7,
    reviews: 60,
    dietaryTags: ['pescetarian'],
    matchIngredients: [
      'rice-noodles',
      'shrimp',
      'squid',
      'oysters',
      'tinapa',
      'chicharon',
      'egg',
      'annatto',
    ],
    ingredients: [
      { name: 'Thick rice noodles, soaked and boiled', amount: '500g' },
      { name: 'Shrimp juice', amount: '2 cups' },
      { name: 'Annatto oil', amount: '1/4 cup' },
      { name: 'Fish sauce', amount: '2 tbsp' },
      { name: 'Shrimp, blanched', amount: '1 cup' },
      { name: 'Squid rings, blanched', amount: '1 cup' },
      { name: 'Oysters (optional)', amount: '1/2 cup' },
      { name: 'Tinapa flakes', amount: '1/2 cup' },
      { name: 'Chicharon, crushed', amount: '1 cup' },
      { name: 'Eggs, boiled and sliced', amount: '3 pcs' },
      { name: 'Pechay Baguio (Napa Cabbage)', amount: '1 cup' },
    ],
    steps: [
      'In a large wok, combine shrimp juice, annatto oil, and fish sauce. Bring to a boil.',
      'Add the cooked noodles and toss until fully coated with the sauce.',
      'Transfer to a platter.',
      'Top generously with shrimp, squid, oysters, tinapa, chicharon, eggs, and cabbage.',
      'Serve with calamansi.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/pancit-malabon',
    nutrition: { calories: 480, protein: 25, carbs: 60, fat: 18, fiber: 3, sodium: 900 },
  },
  {
    id: 'suman-malagkit',
    slug: 'suman-malagkit-rice-cake',
    title: 'Suman Malagkit',
    summary: 'Sticky rice cake wrapped in banana leaves.',
    description:
      'A classic kakanin. Glutinous rice is cooked in coconut milk and sugar, wrapped in banana leaves, and steamed. Chewy, sweet, and fragrant.',
    heroImage: '/images/recipes/suman.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 10,
    prepTime: '30 mins',
    cookTime: '1 hr',
    totalTime: '1 hr 30 mins',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviews: 70,
    dietaryTags: ['vegetarian', 'gluten-free', 'vegan'],
    matchIngredients: ['glutinous-rice', 'coconut-milk', 'sugar', 'banana-leaves'],
    ingredients: [
      { name: 'Glutinous rice', amount: '3 cups' },
      { name: 'Coconut milk', amount: '3 cups' },
      { name: 'Sugar', amount: '1/2 cup' },
      { name: 'Salt', amount: '1 tsp' },
      { name: 'Banana leaves', amount: 'for wrapping' },
    ],
    steps: [
      'Soak rice for 1 hour. Drain.',
      'In a pan, cook rice with coconut milk, sugar, and salt until half-cooked and liquid is absorbed.',
      'Prepare banana leaves (pass over flame to soften).',
      'Place 2-3 tbsp of rice mixture on a leaf.',
      'Fold tightly into a log shape.',
      'Steam for 45 minutes to 1 hour.',
      'Serve with sugar or latik.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/suman-malagkit',
    nutrition: { calories: 220, protein: 3, carbs: 40, fat: 6, fiber: 1, sodium: 150 },
  },
  {
    id: 'hardinera',
    slug: 'hardinera-quezon-meatloaf',
    title: 'Hardinera (Quezon Meatloaf)',
    summary: 'Festive meatloaf from Lucban, Quezon, steamed in oval tins.',
    description:
      "Often confused with Embutido or Menudo, but it's a distinct dish. Diced pork is cooked menudo-style, then mixed with eggs and steamed in llaneras (oval tins) lined with decorative toppings like pineapple and peppers.",
    heroImage: '/images/recipes/hardinera.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 8,
    prepTime: '30 mins',
    cookTime: '1 hr',
    totalTime: '1 hr 30 mins',
    difficulty: 'Advanced',
    rating: 4.6,
    reviews: 40,
    dietaryTags: ['high-protein'],
    matchIngredients: [
      'pork-shoulder',
      'liver-spread',
      'tomato-sauce',
      'pineapple',
      'bell-pepper',
      'egg',
      'cheese',
    ],
    ingredients: [
      { name: 'Pork shoulder, diced', amount: '1 kg' },
      { name: 'Liver spread', amount: '1 can' },
      { name: 'Tomato sauce', amount: '1 cup' },
      { name: 'Pineapple tidbits', amount: '1/2 cup' },
      { name: 'Bell peppers, diced', amount: '1/2 cup' },
      { name: 'Raisins', amount: '1/4 cup' },
      { name: 'Cheese, grated', amount: '1/2 cup' },
      { name: 'Eggs, raw', amount: '4 pcs' },
      { name: 'Boiled eggs & Sliced peppers', amount: 'garnish' },
    ],
    steps: [
      'Sauté pork with garlic and onions.',
      'Add tomato sauce and liver spread. Simmer until cooked. Let cool.',
      'Mix in raw eggs, cheese, raisins, pineapple, and peppers.',
      'Grease llaneras (molds). Arrange boiled egg slices and peppers at the bottom for decoration.',
      'Pour pork mixture into molds.',
      'Cover with foil and steam for 45 minutes.',
      'Invert onto a plate to serve.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/hardinera',
    nutrition: { calories: 380, protein: 28, carbs: 15, fat: 22, fiber: 2, sodium: 680 },
  },
  {
    id: 'goto-beef-tripe',
    slug: 'goto-beef-tripe-porridge',
    title: 'Goto (Beef Tripe Porridge)',
    summary: 'Rice porridge with tender beef tripe, ginger, and garlic.',
    description:
      "A variation of lugaw using beef tripe (tuwalya) and sometimes beef innards. Hearty, warming, and perfect with a side of Tokwa't Baboy.",
    heroImage: '/images/recipes/goto.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 6,
    prepTime: '20 mins',
    cookTime: '2 hrs',
    totalTime: '2 hrs 20 mins',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 85,
    dietaryTags: ['gluten-free'],
    matchIngredients: [
      'beef-tripe',
      'glutinous-rice',
      'ginger',
      'garlic',
      'onion',
      'fish-sauce',
      'calamansi',
    ],
    ingredients: [
      { name: 'Beef tripe (tuwalya), cleaned', amount: '500g' },
      { name: 'Glutinous rice', amount: '1 cup' },
      { name: 'Ginger, julienned', amount: '2 tbsp' },
      { name: 'Garlic, minced', amount: '1 head' },
      { name: 'Onion, chopped', amount: '1 small' },
      { name: 'Beef stock/water', amount: '6 cups' },
      { name: 'Fish sauce', amount: '2 tbsp' },
      { name: 'Safflower (kasubha)', amount: 'pinch' },
    ],
    steps: [
      'Boil tripe with ginger until very tender (1.5 - 2 hours). Slice into strips.',
      'Sauté garlic, onion, and ginger.',
      'Add tripe and rice. Sauté for a minute.',
      'Add beef stock. Simmer until rice is cooked and porridge is thick.',
      'Season with fish sauce and safflower.',
      'Serve with toasted garlic, spring onions, and calamansi.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/goto',
    nutrition: { calories: 300, protein: 18, carbs: 45, fat: 8, fiber: 2, sodium: 650 },
  },
  {
    id: 'fishball-sauce',
    slug: 'fishball-sauce-street-food',
    title: "Manong's Fishball Sauce",
    summary: 'The legendary sweet and spicy brown sauce for street food.',
    description:
      "You can't have fishballs, kikiam, or kwek-kwek without this sauce. A simple mixture of water, soy sauce, sugar, and cornstarch, simmered until thick and glossy.",
    heroImage: '/images/recipes/fishball-sauce.jpg',
    imageAttribution: 'Mix and Munch',
    servings: 10,
    prepTime: '5 mins',
    cookTime: '10 mins',
    totalTime: '15 mins',
    difficulty: 'Easy',
    rating: 5.0,
    reviews: 200,
    dietaryTags: ['vegan', 'vegetarian'],
    matchIngredients: ['soy-sauce', 'sugar', 'cornstarch', 'garlic', 'onion', 'chili'],
    ingredients: [
      { name: 'Water', amount: '2 cups' },
      { name: 'Soy sauce', amount: '2 tbsp' },
      { name: 'Brown sugar', amount: '1/2 cup' },
      { name: 'Cornstarch', amount: '2 tbsp' },
      { name: 'Flour', amount: '1 tbsp' },
      { name: 'Garlic, minced', amount: '2 cloves' },
      { name: 'Onion, minced', amount: '1 small' },
      { name: 'Chili (optional)', amount: 'to taste' },
    ],
    steps: [
      'In a pot, mix water, soy sauce, sugar, cornstarch, flour, garlic, and onion.',
      'Whisk until smooth and no lumps remain.',
      'Place over medium heat.',
      'Stir constantly until the mixture boils and thickens.',
      'Add chili if you want it spicy.',
      'Simmer for 2 minutes.',
      'Serve as a dip for fried street foods.',
    ],
    chef: 'Mix & Munch Kitchen',
    sourceUrl: 'https://mixandmunch.app/recipes/fishball-sauce',
    nutrition: { calories: 45, protein: 0, carbs: 12, fat: 0, fiber: 0, sodium: 150 },
  },
];

// Read existing recipes
let existingRecipes = [];
try {
  const data = fs.readFileSync(RECIPES_PATH, 'utf8');
  existingRecipes = JSON.parse(data);
} catch (err) {
  console.error('Error reading recipes.json:', err);
  process.exit(1);
}

console.log(`Current recipe count: ${existingRecipes.length}`);

// Merge recipes
let addedCount = 0;
newRecipes.forEach((newRecipe) => {
  const exists = existingRecipes.some(
    (r) => r.id === newRecipe.id || r.slug === newRecipe.slug
  );

  if (!exists) {
    existingRecipes.push(newRecipe);
    addedCount++;
    console.log(`Added: ${newRecipe.title}`);
  } else {
    console.log(`Skipped (Duplicate): ${newRecipe.title}`);
  }
});

// Write back to file
try {
  fs.writeFileSync(RECIPES_PATH, JSON.stringify(existingRecipes, null, 2), 'utf8');
  console.log(`\nSuccess! Added ${addedCount} new recipes.`);
  console.log(`Total recipes now: ${existingRecipes.length}`);
} catch (err) {
  console.error('Error writing recipes.json:', err);
}
